const ROLE_LEVELS={trainee:1,volunteer:2,group_leader:3,area_leader:4,service_leader:5,ministry_leader:6,pastor:7};
const ROLE_LABELS={trainee:'Trainee',volunteer:'Standard Volunteer',group_leader:'Group Leader',area_leader:'Area Leader',service_leader:'Service Leader',ministry_leader:'Ministry Leader',pastor:'Ministry Pastor'};
/* LEADERSHIP_PINS removed in v13 - shared plaintext PINs in a client-readable file were never security. Roles + RLS replace them. */
const GROUPS=[
{id:'AMU1',name:'AM Usher Group 1',division:'usher',service:'AM'},{id:'AMU2',name:'AM Usher Group 2',division:'usher',service:'AM'},{id:'AMU3',name:'AM Usher Group 3',division:'usher',service:'AM'},{id:'AMU4',name:'AM Usher Group 4',division:'usher',service:'AM'},{id:'AMU5',name:'AM Usher Group 5',division:'usher',service:'AM'},
{id:'PMU1',name:'PM Usher Group 1',division:'usher',service:'PM'},{id:'PMU2',name:'PM Usher Group 2',division:'usher',service:'PM'},
{id:'AMH1',name:'AM Hostess Group 1',division:'hostess',service:'AM'},{id:'AMH2',name:'AM Hostess Group 2',division:'hostess',service:'AM'},{id:'AMH3',name:'AM Hostess Group 3',division:'hostess',service:'AM'},{id:'AMH4',name:'AM Hostess Group 4',division:'hostess',service:'AM'},{id:'AMH5',name:'AM Hostess Group 5',division:'hostess',service:'AM'},
{id:'PMH1',name:'PM Hostess Group 1',division:'hostess',service:'PM'},{id:'PMH2',name:'PM Hostess Group 2',division:'hostess',service:'PM'},];
const AREA_DUTIES={usher:{Alpha:["Altar Control","Stage Checks","Chair Realignment","Offering Basket Preparation","Offering Basket Support","Front Row Awareness","Leadership Row Support","Altar Call Support","Movement Control Near Stage","Balcony Check"],Bravo:["Foyer Flow","Bathroom Checks","Entrance Control","Balcony Check","Passageway Support","Door Support","Member Direction","Queue Flow"],Charlie:["Welcome Support","Chapel Support","Tent Pathway Support","Outside D3 Support","Stair Support","Exterior Flow","Member Direction","Entrance Greeting"],Delta:["Parking Control","Road Control","Vehicle Guidance","Overflow Parking","Staff Parking Support","Pastor Parking Support","Cone Setup","Banner Setup","Gate Support","Traffic Flow"],Echo:["Main Gate Control","Bus Control","Pedestrian Crossing","Outside Paving Support","Road Paving Support","Staff Parking Road Support","Road Movement Support","AM Foxtrot Coverage"],Foxtrot:["Top Parking Control","Drop-Off Management","PM Road Control","Charlie Road Support","Vehicle Movement","Crowd Flow"]},hostess:{"Inside Group 1":["Stage Cleaning","Stage Rim Cleaning","Speaker Cleaning","Pulpit Cleaning","Backstage Cleaning","Back Corridor Cleaning","Storeroom Check","Clipboard Preparation","FTV Form Setup","Tithing Envelope Setup"],"Inside Group 2":["Auditorium Cleaning","Chair Cleaning","Aisle Cleaning","Stair Cleaning","Rail Cleaning","Balcony Check","After-Service Rubbish Collection","Bottle Pickup","Wrapper Pickup","Tissue Pickup"],"Inside Group 3":["Mother’s Room Cleaning","Parent Room Support","Toy Sanitising","Counter Cleaning","Window Cleaning","Balcony Cleaning","Bin Emptying","Smell Check","Parent Assistance","Door Help","Pram Help"],"Outside Group 1":["Bathroom Cleaning","Bathroom Restocking","Mirror Cleaning","Counter Cleaning","Toilet Cleaning","Floor Mopping","Window Cleaning","Stair Cleaning","Rail Cleaning","Storeroom Restock","Supply Check"],"Outside Group 2":["Tent Support","Tent Cleaning","Greeting","Outside Cleaning","Member Assistance","Rubbish Pickup","AM Tent Setup","AM Tent Reset"],"Outside Group 3":["PM Tent Support","Kids Church Cleaning","Old Foyer Cleaning","Old Bathroom Cleaning","Greeting","Tent Cleaning","After-Service Set Down","Wash Lappies","Wash Mop Covers","Hang Items To Dry"]}};
const DUTY_OPTIONS={usher:Object.entries(AREA_DUTIES.usher).flatMap(([area,titles])=>titles.map(title=>({area,title,description:`${title} in ${area}`}))),hostess:Object.entries(AREA_DUTIES.hostess).flatMap(([area,titles])=>titles.map(title=>({area,title,description:`${title} in ${area}`})))};
const HOSTESS_MODULES=[
{ id:'m1', title:'Attire, Groups & Serving Times', summary:'Dress standards, leadership expectations, group assignment and AM/PM service times.', lessons:['HIT wears all black: black formal pants, black shirt with no crop/open shoulder style, and black formal shoes with no open toes.','Hostesses with red shirts wear black formal pants, clean red shirt with no stains/burn marks, and black formal shoes.','Hair should not be bright colours and should preferably be tied down/up. Earrings must be small, not bright, and not dangling.','AM: arrival 06:00, MOH pre-prayer 07:00, church pre-prayer 07:45, service 08:30 summer / 09:00 winter. PM: arrival 15:30, MOH pre-prayer 16:00, church pre-prayer 17:30, service 18:00.'], quiz:[
['What must Hostesses in Training wear?','All black formal clothing','Red shirt and jeans','Any smart outfit','Sportswear',0],['What type of shoes are not allowed?','Open-toed shoes','Black formal shoes','Closed formal shoes','Flat black shoes',0],['What should hair avoid?','Bright colours','Being tied up','Natural colours','Being neat',0],['Earrings should be…','Small and not dangling','Large and bright','Dangling','Any style',0],['Who guides you after group assignment?','Group leader','Random volunteer','Media team','Only pastor',0],['AM arrival time is…','06:00 AM','07:45 AM','08:30 AM','03:30 PM',0],['PM arrival time is…','03:30 PM','04:00 PM','05:30 PM','06:00 PM',0],['AM MOH pre-prayer is…','07:00 AM','06:00 AM','07:45 AM','09:00 AM',0],['PM service starts at…','06:00 PM','05:30 PM','04:00 PM','03:30 PM',0],['Inside hostesses should be inside before church pre-prayer by…','5–10 minutes','1 hour','After worship','Only after preaching',0]] },
{ id:'m2', title:'Storeroom & Equipment', summary:'Main storeroom, cleaning products, lappies, mop heads, brooms and bathroom storerooms.', lessons:['Treat all equipment with care and respect, return it where you found it, and care for it while in use.','Cleaning products include Windowlene, surface cleaner and floor cleaner. Red lappies are used for surfaces, windows and mirrors.','Noodle mop heads mop the floor, flat mop heads dry the floor, and mop stems are on the walls.','Inside brooms have soft bristles and stay inside. Outside brooms have hard bristles and stay outside. Bathroom storerooms have bathroom-specific carriers and supplies.'], quiz:[
['Which product is used for windows and mirrors?','Windowlene','Floor cleaner','Air freshener','Mr Sheen only',0],['Which cleaner is mixed with water for floors?','Floor cleaner','Windowlene','Surface cleaner only','Hand soap',0],['Red lappies are used for…','Surfaces, windows and mirrors','Floors only','Throwing away','Shoes only',0],['Noodle mop heads are normally used to…','Mop floors','Dry floors','Clean mirrors','Sweep stairs',0],['Flat mop heads are normally used to…','Dry floors','Clean toilets','Spray windows','Hold doors',0],['Inside brooms should be used…','Only inside','Only outside','Anywhere','Only bathrooms',0],['Outside brooms have…','Hard bristles','Soft bristles','No bristles','Blue labels',0],['Bathroom storerooms are next to…','Upstairs and downstairs bathrooms','The stage','The parking lot','The pulpit',0],['Bathroom carriers include…','Windowlene, surface cleaner, floor cleaner, bags, key and gloves','Only water','Only towels','Only chairs',0],['After using equipment you should…','Return it where it belongs','Leave it anywhere','Take it home','Hide it',0]] },
{ id:'m3', title:'Setup & Leadership', summary:'How to use equipment correctly and how leadership flows during setup.', lessons:['All duties must be completed before the church’s pre-prayer.','Use red lappies for everything except floors. Use Windowlene for windows with a clean lappie.','Use surface cleaner for counters, handrails, toilets and non-glass surfaces. Use floor cleaner in water for floors and place wet floor signs.','Your group leader is your main leader. Above them are area leaders, service leader, ministry leaders and Pastor Pieter. Respect leaders from AM or PM when serving together.'], quiz:[
['All setup duties should be completed before…','Church pre-prayer','The sermon','After service','Offering',0],['Red lappies are used for everything except…','Floors','Counters','Handrails','Windows',0],['What should be used for windows?','Windowlene and clean lappie','Floor cleaner','Dirty mop','Surface cleaner only',0],['What must be placed when mopping?','Wet floor sign','Chair','Basket','Clipboard',0],['Who is your main leader in your group?','Group leader','Visitor','Media person','Random member',0],['Above group leaders are…','Area leaders, service leader, ministry leaders and Pastor Pieter','Only trainees','No one','Only security',0],['If an AM leader serves in PM, you should…','Respect them as a leader','Ignore them','Only listen if same group','Tell them to leave',0],['Surface cleaner is used for…','Counters, handrails, toilets and surfaces','Floors only','Glass only','Shoes',0],['Mop heads should be washed and hung…','Behind downstairs bathrooms','In auditorium seats','In the parking lot','At home',0],['Brooms can be effective for…','Auditorium stairs and foyer messes','Cleaning mirrors','Pulpit glass','Toilet paper holders',0]] },
{ id:'m4', title:'During Service Protocols', summary:'Parents room, lights, temperature, outside doors, seating, pre-prayer, praise and worship, altar call.', lessons:['Parents/Baby room requires attentiveness. Keep cleaning products away from children, help parents with doors and prams, wipe the changing station, and do not use your phone.','Mother’s Room temperature should stay at 22–23 degrees. Dim lights during pre-prayer and before service countdown.','Outside doors should be closed during pre-prayer and service to prevent glare. Open doors carefully when people enter/exit. Middle door opens after service, except Praise Party.','During pre-prayer and praise/worship, keep eyes on the congregation, help with tissues/lappies and keep aisles clear. Altar call is sensitive: be kind, attentive and respectful.'], quiz:[
['In Mother’s Room you should not be on your…','Phone','Feet','Post','Team',0],['Cleaning products in children areas should be…','Kept away from children','Left open','Given to children','Placed on toys',0],['Mother’s Room temperature should be…','22–23 degrees','10–12 degrees','30–32 degrees','Any temperature',0],['During service doors should normally be…','Closed and opened only as needed','Wide open always','Locked','Removed',0],['Why keep doors closed during service?','To prevent glare and distraction','To block everyone','To make it dark','To stop worship',0],['Middle door opens…','After service normally','During preaching always','During altar call','Never',0],['Seating goal is to avoid…','Big gaps between people','Full rows','Order','Communication',0],['During prayer hostesses must keep eyes…','Open and on the congregation','Closed only','On the floor only','On phone',0],['During praise and worship people should not stand in…','Aisles','Seats','Rows','Auditorium',0],['Altar call should be handled…','Kindly and sensitively','Roughly','Loudly','Without attention',0]] },
{ id:'m5', title:'Set Down & Feedback', summary:'After-service traffic flow, set down responsibilities and reporting to leaders.', lessons:['After service, help reduce traffic by guiding people out through available doors.','Set down is not optional. AM prepares for PM service and PM cleans the church for the week.','Set down may include scooping the church, taking out bins, packing toys away in Mother’s Room and other duties from leaders.','If you need to leave during set down, inform your leader before leaving. Submit feedback if something is broken, low or needs attention.'], quiz:[
['After service hostesses help reduce…','Traffic','Worship','Leadership','Announcements',0],['Set down for AM helps prepare for…','PM service','Next year','Parking only','No one',0],['Set down for PM helps clean for…','The week','AM only','Media','No reason',0],['Set down includes…','Scooping, bins, toys and assigned duties','Only sitting','Only talking','Only leaving',0],['If you need to leave during set down…','Inform your leader','Leave quietly','Text a friend only','Ignore it',0],['Feedback should be submitted when…','Something is broken, low or concerning','Everything is perfect only','You feel bored','Never',0],['Traffic can be reduced by…','Guiding people to available doors','Closing every door','Blocking exits','Standing still',0],['Set down should not be…','Neglected','Organized','Completed','Communicated',0],['Mother’s Room set down can include…','Packing toys away','Opening parking','Altar call','Media cables',0],['Feedback should be…','Clear and useful','Hidden','Angry only','No location',0]] },
{ id:'m6', title:'Discernment & Ministry Protocol', summary:'Spiritual sensitivity, teamwork, ministry time and how to serve without distracting.', lessons:['During service, be aligned with the Holy Spirit and remember the purpose is God’s glory.','During ministry time, keep serving the people and do not leave your area unattended. If needed, ask another hostess or leader to cover.','Keep watch on the congregation, have tissues and lappies ready and work with fellow ushers and hostesses.','Remove obstacles without disrupting or drawing attention to yourself or others. Rely on the team and ask for help.'], quiz:[
['During ministry time remember you serve…','The people, not yourself','Only yourself','Only leaders','Only guests you know',0],['If you get caught in spirit while posted…','Inform another hostess or leader to cover','Leave area unattended','Ignore everyone','Go home',0],['During altar ministry keep watch on…','The congregation too','Only stage lights','Only your phone','Only the floor',0],['You should keep ready…','Tissues and lappies','Snacks','Headphones','Nothing',0],['Obstacles should be removed…','Without disruption or attention','Loudly','By shouting','Only later',0],['If you make a mistake…','Carry on and learn','Quit immediately','Hide forever','Blame others',0],['You should rely on…','The team','Only yourself','Visitors','No one',0],['Pre-prayer gives volunteers a chance to…','Worship, pray and encounter God before service','Skip service','Rest only','Avoid duties',0],['During service you must be…','Sensitive to surroundings','Distracted','On phone','Absent',0],['All of this is for…','God’s glory','Personal fame','Control','Noise',0]] }
];
const FINAL_QUESTIONS=[]; HOSTESS_MODULES.forEach(m=>m.quiz.slice(0,5).forEach(q=>FINAL_QUESTIONS.push(q)));
const USHER_GUIDES=[
{title:'Alpha — Inside Group 1',items:['Everything inside, stage checks, chair realignment, offering baskets, altar control and balcony cleaning.','Keep inside movement calm and support leaders during altar moments.']},
{title:'Bravo — Inside Team 2',items:['Bathrooms near D3 and MD2, balcony exit near offices, coffee balcony, outside foyer and auditorium door passage.']},
{title:'Charlie — Exterior Welcome',items:['Outside auditorium, sweeping paving, stairs, bathroom by tent, welcoming members from drop-off and chapel entrance.']},
{title:'Delta — Parking',items:['Main road banners, cones, overflow parking, staff parking, Bravo old gate, pastors parking and T-junction gate.']},
{title:'Echo — Road Duties',items:['Main entrance gate, buses, pedestrian crossing, outside paving, road to Delta and AM Foxtrot coverage.']},
{title:'Foxtrot — PM Outside Group 3',items:['PM road control, top parking, drop-off parking, support Charlie and manage flow around the building.']}
];
const HOSTESS_GUIDES=[
{title:'Attire & Serving Times',items:['HIT wears all black formal clothing. Hostesses wear black formal pants, clean red shirt and black formal shoes.','AM arrival 06:00, MOH pre-prayer 07:00, church pre-prayer 07:45, service 08:30/09:00. PM arrival 15:30, MOH pre-prayer 16:00, church pre-prayer 17:30, service 18:00.']},
{title:'Storeroom & Equipment',items:['Windowlene is blue liquid for mirrors/windows. Surface cleaner and floor cleaner are green liquids.','Noodle mop heads mop floors. Flat mop heads dry floors. Red lappies are for surfaces, windows and bathroom mirrors.']},
{title:'Stage Cleaning',items:['Use 2 blue flat mops, 1 string mop, black bucket and floor cleaner. Max 3 sprays. Mop, dry and shine.']},
{title:'Pulpit Cleaning',items:['Ask Service Leader for pulpit lappies. Use damp and dry lappies. Wipe horizontally. Do not use Windowlene.']},
{title:'Mother’s Room',items:['Keep products away from children, help parents, wipe changing station, keep temperature at 22–23 degrees, sanitize toys and do not use phone.']},
{title:'During Service',items:['Keep eyes open during prayer and watch congregation. Help with tissues and lappies. Keep aisles clear during praise and worship. Altar call is sensitive: be kind.']},
{title:'Set Down',items:['Help reduce traffic after service. AM prepares for PM, PM cleans for the week. Inform leader if leaving during set down.']}
];
const LEADERSHIP_GUIDES=[
{title:'Creating Serving Requests',items:['Create a request with title, date, time, deadline and message. Sunday poll normally opens Tuesday and closes Thursday night.']},
{title:'Duty Assignment',items:['Group Leaders can assign duties to their group in V1. Seating is intentionally excluded.']},
{title:'Feedback Review',items:['Leaders can see submitted feedback, identify recurring issues and escalate when needed.']}
];
const EQUIPMENT_GUIDES=[
{title:'Cleaning Products',items:['Windowlene: windows and mirrors. Surface cleaner: counters, handrails, toilets and surfaces. Floor cleaner: floors mixed with water.']},
{title:'Mops & Brooms',items:['Noodle mop for mopping. Flat mop for drying. Inside brooms are soft. Outside brooms are hard and stay outside.']},
{title:'Bathroom Storerooms',items:['Upstairs and downstairs bathroom storerooms have bathroom-specific carriers with Windowlene, surface cleaner, floor cleaner, bags, key and gloves.']}
];
const SEEDED_REQUESTS=[{id:'req_sunday_am',title:'Sunday AM Service',date:'2026-06-14',time:'08:30',deadline:'Thursday 21:00',message:'Please confirm availability for this Sunday. Choose AM, PM, Both or Not Serving.',status:'open',createdAt:new Date().toISOString()}];
